### ISSUE TITLE
NoMethodError: undefined method `state' for nil:NilClass

### ISSUE THREAD

**Issue by ts-3156** [ts-3156/egotter#309]
## Summary

This patch fixes `NoMethodError: undefined method state for nil:NilClass`. 

I chose the easiest way to fix this error. However, it may be better to choose the other way that don't call `transaction.before_commit_records` in `#commit_transaction` when `@stack` is empty.

- Rails 5.1.6.1
- ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
- MySQL 5.6.34

## Steps to reproduce

I can't reproduce this error maybe because this error is caused by race condition... This error occurs once in thousands in my app. I cannot say for sure but It seems like this error is caused by `Timeout.timeout`.

## Relevant code in Rails gem

[rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb)

```ruby
def within_new_transaction(options = {})
  transaction = begin_transaction options
  yield
rescue Exception => error
  if transaction
    rollback_transaction
    after_failure_actions(transaction, error)
  end
  raise
ensure
  unless error
    if Thread.current.status == 'aborting'
      rollback_transaction if transaction
    else
      begin
        commit_transaction
      rescue Exception # <- # NoMethodError undefined method `before_commit_records' for nil:NilClass
        rollback_transaction(transaction) unless transaction.state.completed? # <- NoMethodError undefined method `state' for nil:NilClass
        raise
      end
    end
  end
end
```

## Stacktrace

NoMethodError: undefined method `state' for nil:NilClass

```
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:209:in `rescue in ensure in block in within_new_transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:206:in `ensure in block in within_new_transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:206:in `block in within_new_transaction'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:210:in `transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:313:in `save!'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/suppressor.rb:46:in `save!'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/active_record_prepend.rb:22:in `block in save!'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/transaction.rb:813:in `with_database_metric_name'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent.rb:639:in `with_database_metric_name'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/active_record_prepend.rb:21:in `save!'
/var/egotter/app/workers/update_audience_insight_worker.rb:38:in `perform'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/var/egotter/config/initializers/sidekiq.rb:73:in `block in call'
/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/var/egotter/config/initializers/sidekiq.rb:72:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/config/initializers/sidekiq.rb:101:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/config/initializers/sidekiq.rb:33:in `perform'
/var/egotter/config/initializers/sidekiq.rb:45:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/rollbar-2.18.2/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/reloader.rb:68:in `block in wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/reloader.rb:67:in `wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by ts-3156** [comment]
## Title

ActiveRecord: Fix NoMethodError: undefined method `state' for nil:NilClass

## Summary

This patch fixes `NoMethodError: undefined method state for nil:NilClass`. 

I chose the easiest way to fix this error. However, it may be better to choose the other way that don't call `transaction.before_commit_records` in `#commit_transaction` when `@stack` is empty.

- Rails 5.1.6.1
- ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
- MySQL 5.6.34

## Steps to reproduce

I can't reproduce this error maybe because this error is caused by race condition... This error occurs once in thousands in my app. I cannot say for sure but It seems like this error is caused by `Timeout.timeout`.

## Relevant code in Rails gem

[rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb)

I fixed `NoMethodError undefined method 'state' for nil:NilClass`, but this error is caused by `NoMethodError undefined method 'before_commit_records' for nil:NilClass`.

As above, if I want to solve the actual cause of the problem, I probably should fix `#commit_transaction` to not call `transaction.before_commit_records` when `@stack` is empty.

```ruby
def within_new_transaction(options = {})
  @connection.lock.synchronize do
    transaction = begin_transaction options
    yield
  rescue Exception => error
    if transaction
      rollback_transaction
      after_failure_actions(transaction, error)
    end
    raise
  ensure
    if !error && transaction
      if Thread.current.status == "aborting"
        rollback_transaction
      else
        begin
          commit_transaction
        rescue Exception # <- # NoMethodError undefined method `before_commit_records' for nil:NilClass
          rollback_transaction(transaction) unless transaction.state.completed? # <- NoMethodError undefined method `state' for nil:NilClass
          raise
        end
      end
    end
  end
end

```

## Stacktrace

NoMethodError: undefined method `state' for nil:NilClass


```
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:209:in `rescue in ensure in block in within_new_transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:206:in `ensure in block in within_new_transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:206:in `block in within_new_transaction'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:210:in `transaction'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/transactions.rb:313:in `save!'
/var/egotter/.bundle/ruby/2.5.0/gems/activerecord-5.1.6.1/lib/active_record/suppressor.rb:46:in `save!'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/active_record_prepend.rb:22:in `block in save!'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/transaction.rb:813:in `with_database_metric_name'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent.rb:639:in `with_database_metric_name'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/active_record_prepend.rb:21:in `save!'
/var/egotter/app/workers/update_audience_insight_worker.rb:38:in `perform'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/var/egotter/config/initializers/sidekiq.rb:73:in `block in call'
/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:33:in `catch'
/usr/local/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
/var/egotter/config/initializers/sidekiq.rb:72:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/config/initializers/sidekiq.rb:101:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/config/initializers/sidekiq.rb:33:in `perform'
/var/egotter/config/initializers/sidekiq.rb:45:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/rollbar-2.18.2/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
/var/egotter/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.0.0.351/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/reloader.rb:68:in `block in wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/activesupport-5.1.6.1/lib/active_support/reloader.rb:67:in `wrap'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
/var/egotter/.bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```
